# Generated by Django 5.2.4 on 2025-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_prodctcoller'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodctcoller',
            name='is_avalable',
            field=models.BooleanField(default=True),
        ),
    ]
