# Generated by Django 5.2.4 on 2025-08-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='update_at',
        ),
    ]
