# Generated by Django 5.2.4 on 2025-08-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_update_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdctColler',
            new_name='ProdctPakage',
        ),
    ]
