# Generated by Django 5.2.4 on 2025-08-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='min_coler',
            new_name='coler',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='min_final_price',
            new_name='final_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='min_price',
            new_name='price',
        ),
    ]
