# Generated by Django 5.2.4 on 2025-08-19 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_min_coler_product_coler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProdctPakage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coler', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('final_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('is_avalable', models.BooleanField(default=True)),
                ('product_number', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pakages', to='product.product')),
            ],
        ),
    ]
