# Generated by Django 5.2.4 on 2025-08-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_discount_prodctpakage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coler',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
