# Generated by Django 5.2.4 on 2025-08-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodctpakage',
            name='coler_hex',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
