# Generated by Django 5.2.4 on 2025-08-30 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_prodctpakage_coler_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodctpakage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packages', to='product.product'),
        ),
    ]
