# Generated by Django 5.2.4 on 2025-09-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_prodctpakage_is_avalable_product_is_avalable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_avalable',
        ),
        migrations.AddField(
            model_name='prodctpakage',
            name='is_avalable',
            field=models.BooleanField(default=True),
        ),
    ]
