# Generated by Django 5.2.4 on 2025-09-05 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_product_is_avalable_prodctpakage_is_avalable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodctpakage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='product.product'),
        ),
    ]
