# Generated by Django 5.2.4 on 2025-09-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_prodctpakage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
