# Generated by Django 5.2.4 on 2025-09-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coler',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
